# This file is machine-generated - editing it directly is not advised

[[ProxyInterface]]
path = "D:\\ProjectsJulia\\\\ProxyInterface\\\\"
uuid = "90c4b210-f34a-11e9-1a87-5d0d3aaf0cab"
version = "0.1.0"

[[SimpleMatch]]
path = "D:\\ProjectsJulia\\\\SimpleMatch\\\\"
uuid = "a3ae8450-d22f-11e9-3fe0-77240e25996f"
version = "0.1.0"

[[StructEquality]]
deps = ["SimpleMatch"]
path = "D:\\ProjectsJulia\\\\StructEquality\\\\"
uuid = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"
version = "0.1.0"
