name = "ExprParsers"
uuid = "c5caad1f-83bd-4ce8-ac8e-4b29921e994e"
authors = ["Sahm Stephan <stephan.sahm@gmx.de>"]
version = "1.2.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
ProxyInterfaces = "9b3bf0c4-f070-48bc-ae01-f2584e9c23bc"
SimpleMatch = "a3ae8450-d22f-11e9-3fe0-77240e25996f"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"

[compat]
Compat = "2.1, 3, 4"
ProxyInterfaces = "1"
SimpleMatch = "1"
StructEquality = "2"
julia = "1.6"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
