name = "ExprParsers"
uuid = "c5caad1f-83bd-4ce8-ac8e-4b29921e994e"
authors = ["Sahm Stephan <stephan.sahm@gmx.de>"]
version = "1.0.0"

[deps]
ProxyInterface = "90c4b210-f34a-11e9-1a87-5d0d3aaf0cab"
SimpleMatch = "a3ae8450-d22f-11e9-3fe0-77240e25996f"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
